export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
import './globals.css';


// This will always be present and is regenerated automatically if deleted
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <header className='bg-pink-500 w-full h-[150px]'>Header</header>
                <div className='flex items-center justify-center h-[150px] w-full'>
                    {children}
                </div>
                <footer className='bg-yellow-500 w-full h-[150px]'>footer</footer>
            </body>
        </html>
    )
}
